apiVersion: v2
name: agentlens
description: AgentLens â€” observability platform for AI agents
type: application
version: 0.1.0
appVersion: "0.9.0"

dependencies:
  - name: postgresql
    version: "~16.x"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled

  - name: redis
    version: "~20.x"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
